.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH BIOSDEVNAME 1 "Jul 27, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
biosdevname \- give BIOS-given name of a device
.SH SYNOPSIS
.B biosdevname
.RI [options]\ [args]...
.SH DESCRIPTION
biosdevname takes a kernel device name as an
argument, and returns the BIOS-given name it "should" be.
.SH OPTIONS
.TP
.B \-i, \-\-interface
Treat [args] as ethernet devs
.TP
.B \-d, \-\-debug
Enable debugging
.TP
.B \-\-policy \fI[physical|all_ethN]
.TP
.B \-\-prefix \fI[string]
string use for embedded NICs in the physical policy (default=em)
.SH SEE ALSO
.br
http://linux.dell.com/files/biosdevname/
.SH AUTHOR
biosdevname was written by  Matt Domsch <Matt_Domsch@dell.com>
.PP
This manual page was written by Rudy Gevaert <Rudy.Gevaert@UGent.be>,
for the Debian project (but may be used by others).
